name: cryptoutils
version: 0.3.0
author: Steven Roose <stevenroose@gmail.com>
description: A crypto utility library.
homepage: https://github.com/stevenroose/dart-cryptoutils
dependencies:
  collection: ">=1.1.1 <2.0.0"

dev_dependencies:
  test: any
